USE [master]
GO

/****** Object:  Database [FormularionFin4teen]    Script Date: 03/12/2021 18:58:37 ******/
CREATE DATABASE [FormularionFin4teen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FormularionFin4teen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2\MSSQL\DATA\FormularionFin4teen.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FormularionFin4teen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER2\MSSQL\DATA\FormularionFin4teen_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FormularionFin4teen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FormularionFin4teen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET ARITHABORT OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FormularionFin4teen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FormularionFin4teen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FormularionFin4teen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FormularionFin4teen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FormularionFin4teen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FormularionFin4teen] SET  MULTI_USER 
GO

ALTER DATABASE [FormularionFin4teen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FormularionFin4teen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FormularionFin4teen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FormularionFin4teen] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FormularionFin4teen] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FormularionFin4teen] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FormularionFin4teen] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FormularionFin4teen] SET  READ_WRITE 
GO

